### PR TITLE
express-openapi: Bumping openapi-framework to 0.2.0 for ajv performance.

### PR DESCRIPTION
**Pull request by jsdevel**

### CODE REVIEW

**Comment by srijs** [comment]
Looks like tests are failing to due changes in error messages. Let me know if you want help to fix these up!

**Comment by jsdevel** [comment]
Thanks!  I think I may need help on a few of them.  I updated the easy ones.  I did notice that ajv appears to sometimes wrap with single quotes vs double.

**Comment by jsdevel** [comment]
@srijs can you look at these?

```
  1) express-openapisample-projects
       with-errorMiddleware
         "before all" hook:
     can't resolve reference #/definitions/Foo from id #

  2) express-openapisample-projects
       with-external-schema-references
         "before all" hook:
     Error: unknown format "int32" is used in schema at path "#/properties/age"
      at Object.generate_format [as code] (node_modules/ajv/lib/dotjs/format.js:69:15)
      at Object.generate_validate [as validate] (node_modules/ajv/lib/dotjs/validate.js:334:35)
      at Object.generate_properties [as code] (node_modules/ajv/lib/dotjs/properties.js:194:26)
      at generate_validate (node_modules/ajv/lib/dotjs/validate.js:334:35)
      at localCompile (node_modules/ajv/lib/compile/index.js:88:22)
      at Ajv.compile (node_modules/ajv/lib/compile/index.js:55:13)
      at Ajv._compile (node_modules/ajv/lib/ajv.js:353:27)
      at Ajv.resolveSchema (node_modules/ajv/lib/compile/resolve.js:84:36)
      at Ajv.getJsonPointer (node_modules/ajv/lib/compile/resolve.js:134:35)
      at Ajv.resolveSchema (node_modules/ajv/lib/compile/resolve.js:95:25)
      at Ajv.resolve (node_modules/ajv/lib/compile/resolve.js:41:27)
      at Object.resolveRef (node_modules/ajv/lib/compile/index.js:189:21)
      at Object.generate_ref [as code] (node_modules/ajv/lib/dotjs/ref.js:21:22)
      at Object.generate_validate [as validate] (node_modules/ajv/lib/dotjs/validate.js:261:37)
      at Object.generate_items [as code] (node_modules/ajv/lib/dotjs/items.js:123:20)
      at Object.generate_validate [as validate] (node_modules/ajv/lib/dotjs/validate.js:334:35)
      at Object.generate_properties [as code] (node_modules/ajv/lib/dotjs/properties.js:194:26)
      at generate_validate (node_modules/ajv/lib/dotjs/validate.js:334:35)
      at localCompile (node_modules/ajv/lib/compile/index.js:88:22)
      at Ajv.compile (node_modules/ajv/lib/compile/index.js:55:13)
      at Ajv._compile (node_modules/ajv/lib/ajv.js:353:27)
      at Ajv.compile (node_modules/ajv/lib/ajv.js:113:37)
      at /home/travis/build/kogosoftwarellc/open-api/packages/express-openapi/node_modules/openapi-framework/node_modules/openapi-response-validator/index.js:85:26
      at Array.forEach (<anonymous>)
      at compileValidators (node_modules/openapi-framework/node_modules/openapi-response-validator/index.js:84:24)
      at new OpenapiResponseValidator (node_modules/openapi-framework/node_modules/openapi-response-validator/index.js:42:21)
      at /home/travis/build/kogosoftwarellc/open-api/packages/express-openapi/node_modules/openapi-framework/dist/index.js:167:49
      at Array.forEach (<anonymous>)
      at /home/travis/build/kogosoftwarellc/open-api/packages/express-openapi/node_modules/openapi-framework/dist/index.js:135:62
      at Array.forEach (<anonymous>)
      at OpenapiFramework.initialize (node_modules/openapi-framework/dist/index.js:119:16)
      at Object.initialize (index.js:9:4476)
      at Object.<anonymous> (test/sample-projects/with-external-schema-references/app.js:11:9)
      at Object.Module._extensions.(anonymous function) [as .js] (/home/travis/build/kogosoftwarellc/open-api/node_modules/istanbul/lib/hook.js:109:37)
      at require (internal/module.js:11:18)
      at Context.<anonymous> (test/sample-projects/with-external-schema-references/spec.js:7:9)
```

**Comment by jsdevel** [comment]
Actually, this wasn't an error.  Looks like the response validator found an invalid test!  nice!

```
  1) express-openapisample-projects
       with-errorMiddleware
         "before all" hook:
     can't resolve reference #/definitions/Foo from id #
```

**Comment by jsdevel** [comment]
@srijs so I think I figured it out.  Looks like `jsonschema` would ignore unknown formats.  `ajv` appears to require formatters for any custom format.  Can you confirm this?  We'll likely need to follow up with this and perhaps provide some default formatters for the ones specified in the [OpenAPI specification](https://swagger.io/specification/#dataTypes).

**Comment by srijs** [comment]
Opened #171 which should ignore all custom OpenAPI formats for now. We can follow up with custom validators at a later point.

**Comment by jsdevel** [comment]
yea, since they weren't really handled before, we'll probably just target a future major release where we can require them by default, then allow `args.ignoreUnknownFormats` to be passed or something.

**Comment by jsdevel** [comment]
Thanks again @srijs !  Published as `express-openapi@2.0.0`

**Pull request merged**
