### PR TITLE
Add pathsobject v3 extension

### PR DESCRIPTION
**Pull request by yordis**
*Note: This checklist isn't meant to show up on the actual Pull Request (PR). It is added here to make you aware of items our maintainers will look for when reviewing your PR.  If your PR is missing any of these items it will be rejected!  Please delete this message and the following checklist and replace it with your own message as you see fit.*

- [x] I only have 1 commit.
- [x] My commit is prefixed with the relevant package (e.g. `express-openapi: fixing something`) *Note: You can use the bin/commit script to automate this.*
- [ ] I have added tests.
- [ ] I'm using the latest code from the master branch and there are no conflicts on my branch.
- [ ] I have added a suffix to my commit message that will close any existing issue my PR addresses (e.g. `openapi-jsonschema-parameters: Adding examples to the validation keywords (fixes #455)`).
- [ ] My tests pass locally.
- [x] I have run linting against my code.

### CODE REVIEW

**Comment by yordis** [comment]
@jsdevel hey mate, would you mind give me a hand with this PR? 🙏🏻

**Comment by jsdevel** [comment]
what is the purpose for this?

**Comment by yordis** [comment]
@jsdevel we have some custom metadata at the `PathItem` level: https://github.com/straw-hat-team/openapi-web-sdk-generator/blob/0cf267c0a8582552d8fc98be1b9a6fb60a1a70ea/src/types.ts#L8-L12

So currently there is no way to extend PathItem without creating more aliases, I would like to do what Operation does https://github.com/kogosoftwarellc/open-api/blob/1b56b57bc6417f36aa8a6af1b83dcb9720113070/packages/openapi-types/index.ts#L122

**Comment by yordis** [comment]
Hey @jsdevel is this change release? I have the latest version and I don't see so I am just confirming, would appreciate it if you cut a release if you haven't 🙏🏻

**Pull request merged**
