### PR TITLE
openapi-request-validator: pass schema definitions for v3 (closes #280)

### LINKED ISSUE #280: can't resolve reference to a schema component for requestBody
GET and POST reference the same schema component, GET works fine, but POST fails with the following error:

```
 {
      "message": "can't resolve reference #/components/schemas/Document",
      "location": "body",
      "schema": {
        "$ref": "#/components/schemas/Document"
      }
    }
```
The openapi-doc is as follows, and according to the specification https://swagger.io/docs/specification/describing-request-body/ it should be correct:

```yaml
openapi: "3.0.0"
paths:
    /path/{documentPath}:
        get:
            summary: Returns a document by path
            parameters:
                - name: documentPath
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Document"
                default:
                    description: Error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
        post:
            summary: Create a new document by path
            parameters:
                - name: documentPath
                  in: path
                  required: true
                  schema:
                      type: string
            # https://swagger.io/docs/specification/describing-request-body/
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Document"
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Document"
                default:
                    description: Error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
components:
    schemas:
        Document:
            type: object
            required:
                - path
                - type
                - uid
            properties:
                name:
                    type: string
                title:
                    type: string
                path:
                    type: string
                uid:
                    type: string
                type:
                    type: string
                    enum: ['Folder', 'File', 'Root', 'Picture', 'Domain']
                    default: 'File'
                properties:
                    type: object # key-value pairs
```

### PR DESCRIPTION
**Pull request by mbsimonovic**

### CODE REVIEW

**Comment by jsdevel** [comment]
can you provide a test?

**Comment by jsdevel** [comment]
i'd like the test for this package to be included in this PR

**Comment by mbsimonovic** [comment]
sure, here's also one test here

**Comment by jsdevel** [comment]
You're on fire @mbsimonovic !  Thank you so much!

**Comment by mbsimonovic** [comment]
cool, so next time you publish request validator, and update openapi-framework to use it, i can open the other PR. Or should I open it right now?

**Comment by jsdevel** [comment]
i'm trying to get the tests passing locally, but am having issues.  should have it published soon

**Comment by jsdevel** [comment]
@mbsimonovic are you able to run the tests locally? `./bin/test packages/openapi-request-validator`?

**Comment by mbsimonovic** [comment]
yes, works fine on the master (last commit 48cae40ca3)

**Comment by jsdevel** [comment]
can you try this?

```
open-api (master) $ node --version
v8.15.0
open-api (master) $ npm --version
6.4.1
```

**Comment by jsdevel** [comment]
i'll try with v10

**Comment by jsdevel** [comment]
failing for me on v10 as well.  you're using the latest on master?

**Comment by mbsimonovic** [comment]
yes, the latest, see the commits above

**Comment by mbsimonovic** [comment]
the last travis build is also fine: https://travis-ci.org/kogosoftwarellc/open-api/jobs/478281101

**Comment by mbsimonovic** [comment]
just tested all the packages on a linux droplet and they all passed

**Comment by jsdevel** [comment]
yea, looks like my build wasn't getting updated.  published and bumped in openapi-framework.  thanks for the support!

**Pull request merged**
