### PR TITLE
When using operations, building routes should not duplicate methods being processed

### PR DESCRIPTION
**Pull request by sebasmagri**
wrt #368

### CODE REVIEW

**Comment by jsdevel** [comment]
Thanks @sebasmagri, can you add a test?

**Comment by sebasmagri** [comment]
@jsdevel was actually thinking on how to test this out, since this affects only what's sent to the output. I guess we can override the output stream and check what's there... But that seems a bit hacky for me. Any ideas?

**Comment by jsdevel** [comment]
i suppose you could have a module in the test directory that stores state, like how many times it was called.  then check it's state in the test.

**Comment by jsdevel** [comment]
@sebasmagri any progress?

**Comment by jsdevel** [comment]
@sebasmagri ?

**Comment by sebasmagri** [comment]
Sorry @jsdevel I've been overloaded these days. I'll catch up with this this week...

**Comment by MrKumaPants** [comment]
Could we get this merged in?

**Comment by jsdevel** [comment]
@MrKumaPants i'm waiting on tests to be added.

**Comment by jsdevel** [comment]
@sebasmagri have time to wrap this up?

**Comment by tmeyer-smith** [comment]
Is there an expected time/date for when this will be added?

**Comment by jsdevel** [comment]
> Is there an expected time/date for when this will be added?

@sebasmagri ?

**Comment by sebasmagri** [comment]
@jsdevel I've been unable to find the time to add the tests, so if anyone wants to jump in please feel free and either open a new PR with this changes plus tests or open a PR against the branch in my repo and I'll merge them.

**Comment by jsdevel** [comment]
closed this with #452.  Still need to add tests, but hoping the community can verify that it works.

**Pull request closed without merging**
