### PR TITLE
Bugfix for #280

### PR DESCRIPTION
**Pull request by mbsimonovic**
https://github.com/kogosoftwarellc/open-api/issues/280

### CODE REVIEW

**Comment by jsdevel** [comment]
please provide a description for the issue in one of the commits, and add ` fixes #280` at the end of the description.

i don't have linking setup yet.  i'll merge this pr and publish openapi-request-validator, then you can bump that reference in openapi-framework's dependencies.

**Comment by mbsimonovic** [comment]
done

**Comment by jsdevel** [comment]
i'm still not seeing a description in the commit.  i'd prefer to see something like this:

```
git commit -m "openapi-request-validation: Using requestBody when it's present (fixes #100000)"
```

**Comment by mbsimonovic** [comment]
screen shot 2019-01-08 at 23 48 33

the description is one line below

**Comment by jsdevel** [comment]
can you have the description as the first line in the commit message?  i use that with `git log --oneline` when drafteing the CHANGELOG

**Comment by mbsimonovic** [comment]
sure. now it's a single commit, with a single one-line message

**Comment by mbsimonovic** [comment]
it compiles fine, and all the tests pass:

screen shot 2019-01-09 at 10 36 09


but fails later because openapi-framework now requires a new version of request-validator, which has a changed `OpenAPIRequestValidatorArgs` interface (with `componentSchemas`). That's why I asked how is this solved, when an interface gets changed in one package, and is required in another. To do this w/o build failing, I'd have to create a PR in the validator package, then wait for you to publish it, and then change the openapi-framework package to use the newly published validator package.

**Comment by jsdevel** [comment]
> To do this w/o build failing, I'd have to create a PR in the validator package, then wait for you to publish it, and then change the openapi-framework package to use the newly published validator package.

exactly

On a side note: I'm starting to see that this is painful.  A while back I was looking into using lerna to allow linking.

**Comment by mbsimonovic** [comment]
allright, here's the first PR https://github.com/kogosoftwarellc/open-api/pull/303, so as soon as it gets merged, and new version published, and openapi-framework starts using that new version, i can create the second PR

**Comment by jsdevel** [comment]
thank you @mbsimonovic !

**Pull request closed without merging**
