### PR TITLE
openapi-request-validator: bugfix: handle multipart/form-data (https:…

### PR DESCRIPTION
**Pull request by mbsimonovic**
…//github.com/kogosoftwarellc/open-api/issues/280)

### CODE REVIEW

**Comment by mbsimonovic** [comment]
hm, is it possible that contentType is undefined? in that case the parser will fail and throw an error.

**Comment by mbsimonovic** [comment]
ah, linter fails..

**Comment by jsdevel** [comment]
this is great!  thank you so much @mbsimonovic !

**Comment by mbsimonovic** [comment]
shall we close https://github.com/kogosoftwarellc/open-api/issues/279 ?

**Comment by jsdevel** [comment]
does this close #279?

**Comment by mbsimonovic** [comment]
yes, with the pull request it will properly handle multipart

**Pull request merged**
