### PR TITLE
openapi-response-validator: Set "useDefaults: true" on Ajv

### PR DESCRIPTION
**Pull request by TuckerWhitehouse**
Follow up to #409

### CODE REVIEW

**Comment by jsdevel** [comment]
can you change the commit prefix to response?

**Comment by jsdevel** [comment]
you can use the `bin/commit` script to do this for you, but you'd have to soft reset the last commit now

**Comment by TuckerWhitehouse** [comment]
Whoops, title & commit message updated

**Comment by jsdevel** [comment]
thanks!

**Pull request merged**
