### PR TITLE
openapi-request-validator: fixes circular $ref

### PR DESCRIPTION
**Pull request by AlexHolly**
solves issue of https://github.com/kogosoftwarellc/open-api/pull/472

### CODE REVIEW

**Comment by AlexHolly** [comment]
Any plans on pushing this to npm soon? I would like to use the changes on
`openapi-request-validator` and `openapi-response-validator`, thanks.

**Comment by jsdevel** [comment]
soon.  ping me in a few days if i haven't gotten to it

**Comment by AlexHolly** [comment]
ping,

The github link is broken https://www.npmjs.com/package/openapi-response-validator

**Comment by AlexHolly** [comment]
ping

**Comment by josephgardner** [comment]
@jsdevel can you please publish this? Running into this same issue :(

**Pull request merged**
