### PR TITLE
Bugfix for issue #294

### PR DESCRIPTION
**Pull request by mbsimonovic**
https://github.com/kogosoftwarellc/open-api/issues/294

### CODE REVIEW

**Comment by jsdevel** [comment]
the commits look kind of odd.  why are there release commits herein?

**Comment by mbsimonovic** [comment]
i've only changed the commit messages. guess because i had to merge?

**Comment by jsdevel** [comment]
commits

ideally, i'd like to see 1 commit here

**Comment by mbsimonovic** [comment]
ah here's what happened, i wrote the test and committed, and then you pushed some changes, so i pulled to see if the bug got fixed, but wasn't, so i fixed the bug later. i'm not sure how to squash the first and fourth commit into a single one. would it be ok to accept it as it is now, and i'll try to make it a single commit in the future?

**Comment by mbsimonovic** [comment]
i agree, in retrospect, i should've created another branch to pull your changes and test, before making the bugfix commit, mea culpa, lesson learned.

**Comment by mbsimonovic** [comment]
it's a single commit now

**Comment by jsdevel** [comment]
No worries!  this is great thank you!

**Pull request merged**
