### PR TITLE
openapi-request-validator: fixes circular $ref for items

### PR DESCRIPTION
**Pull request by AlexHolly**
related #565

### CODE REVIEW

**Comment by jsdevel** [comment]
thanks!

**Comment by josephgardner** [comment]
@jsdevel any chance we can get a build with this? Running into this issue as well.

**Comment by jsdevel** [comment]
sorry for the lateness, covid-19 messed everything up.  i'll release soon.  going through the new PRs.

**Comment by AlexHolly** [comment]
ping

**Comment by jsdevel** [comment]
7.0.0 is out.  first release/publish using lerna!  please lmk if it's all working correctly.  now that we have lerna setup, publishes should happen a lot faster.  the old process was too tedious for me.  now it's joyful :joy:

**Pull request merged**
