### PR TITLE
openapi-response-validator: now accepts nullable property + test

### PR DESCRIPTION
**Pull request by funduck**
test case shows error and fails but shouldn't in openapi v3

### CODE REVIEW

**Comment by jsdevel** [comment]
i may be able to fix this tonight

**Comment by funduck** [comment]
I'm a bit confused, did I have to add test case that passes, but doesn't show the problem described in issue or I did right that wrote test case that fails and this is how issue is shown?

**Comment by jsdevel** [comment]
@funduck sorry for the confusion.  This shows how to recreate the issue.  I've been pondering what the right way is to solve this problem.  I'm hoping to have a fix soon.

**Comment by funduck** [comment]
@jsdevel is there something I should do for this pull request to be accepted?

**Comment by jsdevel** [comment]
hey!  sorry i missed this.  i'll take a look tonight.

**Comment by jsdevel** [comment]
Thanks @funduck !  I'll publish soon

**Pull request merged**
