### PR TITLE
Upgrade to typescript 3.5.3

### PR DESCRIPTION
**Pull request by nulltoken**

### CODE REVIEW

**Comment by nulltoken** [comment]
This is a bit weird. I haven't been able to bump it up to 3.6.4.

tsc was complaining about a "Duplicate identifier 'IteratorResult'."

Found some **[evidences](https://stackoverflow.com/questions/57331779/typescript-duplicate-identifier-iteratorresult)** of other people suffering from the same issue, but haven't been able to work around it.

I eventually fell back to 3.5.3

**Comment by nulltoken** [comment]
> I eventually fell back to 3.5.3

Nope. Still hitting some other issues down the road. I tried to tweak the `tsconfig.json` lib entries with no luck.

Would you have any idea?

**Comment by jsdevel** [comment]
i don't sorry

**Comment by nulltoken** [comment]
> i don't sorry

>i don't sorry

I'll see in the following days if I can better troubleshoot the origin of the issue.

**Comment by jsdevel** [comment]
gonna be upgrading to the latest soon, along with lerna

**Pull request closed without merging**
