### PR TITLE
Added

### PR DESCRIPTION
**Pull request by jwmur**
1) support for v3 security handlers and
2) a basepath argument for v3 schemas

### CODE REVIEW

**Comment by jsdevel** [comment]
thanks!  can you add some tests?

**Comment by jsdevel** [comment]
@jwmur you still working this?  going to close soon without tests.

**Comment by jwmur** [comment]
Yes.  Any tips on where similar tests?

**Comment by jsdevel** [comment]
any progress @jwmur ?

**Comment by jwmur** [comment]
Carving out time to write the tests.  I'm still planning on doing.

**Comment by jwmur** [comment]
Will try to get done before the weekend

**Comment by jsdevel** [comment]
Thanks!  also, can you update the commit subject?  i want to be able to track this in git history.

**Comment by jsdevel** [comment]
@bill-kitsune are there ideas here that are relevant to #274 ?

@jwmur ETA on tests?  Also looks like there's conflicts.

**Comment by bill-kitsune** [comment]
@jsdevel I think this approach to the baseUrl in this PR would get people by until #274 is resolved, but I guess doesn't quite "Support the servers attribute" of OpenAPI 3.0.  It seems more like an approach to get people by until the framework supports the servers attribute.

The goal of this library also seems like as much as possible should be derived from the openapi doc, to that end it might be better to split this PR to just the security handlers and then wait for #274 ?

**Comment by bill-kitsune** [comment]
In express at least a way to work around the base path issue until #274 might be something like the following:

```
const apiRouter = express.Router()
expressOpenApi.initialize({
  apiDoc: v1ApiDoc,
  app: apiRouter,
  dependencies: {
  worldsService: WorldsService,
  },
  paths: path.join(__dirname, './api/v1/paths'),
})
this.express.use('/api/v1', apiRouter)
```

**Comment by jsdevel** [comment]
@bill-kitsune I agree.  @jwmur can you limit this PR to the securityHandlers?

**Comment by jsdevel** [comment]
@jwmur: @bill-kitsune has just added support for the servers attribute, we'd love to get your work on the securityHandlers in.  Can you limit this PR to just that?

**Comment by jsdevel** [comment]
@jwmur the work on securityHandlers herein could potentially fix #305.  Are you going to finish this soon?

**Comment by jsdevel** [comment]
@jwmur going to close this due to a lack of response.  we'd love to see support for security handlers, so if you have time to address the issues stated above, please re-open!

**Pull request closed without merging**
