### PR TITLE
openapi-request-validator: always return array (fixes #512)

### LINKED ISSUE #512: Same API for openapi-response-validator and openapi-request-validator 'validate'
I noticed a few differences, is it possible to make them more similar?

- Name both `validate` or `validateRequest / validateResponse`

  - **openapi-request-validator:**

    `validator.validate`

  - **openapi-response-validator:**

    `instance.validateResponse`

- The return type for `validate`:
   
  - in `request-validator` can be an Array or Object.

       https://github.com/kogosoftwarellc/open-api/blob/master/packages/openapi-request-validator/index.ts#L314

  - in `response-validator` is always an Object but sometimes the `errors` key is missing.
       https://github.com/kogosoftwarellc/open-api/blob/master/packages/openapi-response-validator/index.ts#L124
      https://github.com/kogosoftwarellc/open-api/blob/master/packages/openapi-response-validator/index.ts#L132

   It would be nice to always get an Array.

### PR DESCRIPTION
**Pull request by AlexHolly**
- [x ] My tests pass locally.

### CODE REVIEW

**Comment by jsdevel** [comment]
once tests are added i'll look again

**Comment by AlexHolly** [comment]
It still doesn't look right, do you need the `status`?
https://github.com/kogosoftwarellc/open-api/pull/519/files#diff-32b5cc863d07f4a03bd815a69e54f78cR321
It should always have a status (200/400) or never, because an empty array means 200 ...

**Comment by AlexHolly** [comment]
ping

**Comment by jsdevel** [comment]
@AlexHolly i think the purpose behind the original object status was to support epress error middleware i.e. middleware with 4 parameters.

**Comment by AlexHolly** [comment]
I could try to add a flag so it will keep the current api and only return an array if expected.

**Pull request closed without merging**
