### PR TITLE
[WIP] Open xplat development to Windows

### PR DESCRIPTION
**Pull request by nulltoken**
So... this is a work in progress. Which doesn't completely work... yet (hopefully) ;-)

The overall goal is to make it easier for Windows developers to contribute to this project.

Early feedback is welcome!

_Note:_ Even when launched from a `git bash` session, npm on Windows spawns a CMD shell with each `npm run script` call and prepend the PATH with `node_modules/.bin`. As such, when `tsc` is triggered from a `prepare` script (for instance), it is first found within the standard `node_modules/.bin` location. The overridden version that comes from `bin/dev-tools` is thus never leveraged on Windows. Prefixing the custom based versions of `nyc`, `tsc` and `mocha` with `cust_` avoids (in very ugly way) those name collisions.

### CODE REVIEW

**Comment by nulltoken** [comment]
Hmmm.... I think I've hit a wall. I can make `mocha` work, but `nyc` still resists. I've tried different approaches, but in vain.

I was wondering, would you be open to pick a different test runner (eg. jest) which would already include code coverage capabilities? This may help solve this.

Thoughts?

**Comment by jsdevel** [comment]
i'd rather add a `.bash` file extension and just refer to that and make it a requirement that you use a bash shell on windows.  i'm not really in favor of adding bat scripts.

**Comment by nulltoken** [comment]
> i'd rather add a `.bash` file extension and just refer to that and make it a requirement that you use a bash shell on windows. i'm not really in favor of adding bat scripts.

@jsdevel _I_ use a bash shell on Windows. And I having been able to even run the tests.

The issue lies in how npm internally spawns the npm run script invocation. On windows, it spawns a child CMD.exe process even if the initial run has been performed through a bash session.

I haven't found a workaround to mitigate that.

**Comment by jsdevel** [comment]
well, i don't have much desire to add bat files sorry.

**Comment by jsdevel** [comment]
besides, i've been thinking about migrating to lerna, and i see this as complicating that effort.  plus, i doubt anyone is going to maintain these bat files.  i know i won't.

**Comment by jsdevel** [comment]
@nulltoken i'd welcome making the change to lerna.  i'm fine with keeping all the version numbers in sync etc.  right now the project uses independent versioning, but i'm not attached to that.

**Pull request closed without merging**
