### PR TITLE
express-openapi: Set default basePath (issue #376)

### LINKED ISSUE #376: Generated API doc fails Swagger validation when basePath is not set
When configuring express-openapi, if the API's basePath option is not set, the generated API doc has the basePath property set to an empty string, which is invalid according to the swagger.io's online validator (the one used by default in Swagger UI).

According to the spec https://swagger.io/docs/specification/2-0/api-host-and-base-path/ : 
> [basePath] must start with a leading slash /. If basePath is not specified, it defaults to /

### PR DESCRIPTION
**Pull request by Manny651**
Fixes #376

### CODE REVIEW

**Comment by jsdevel** [comment]
can you add this for `koa-openapi` too?

**Comment by Manny651** [comment]
I'm having trouble running the koa-openapi tests; the 8 basic-usage tests pass, then the process hangs forever.

**Comment by jsdevel** [comment]
@Manny651 looks like the `travis-test` script is actually disabled.  not affecting the travis build at all, but prevents me from seeing any error there.

**Comment by jsdevel** [comment]
@Manny651 can you change the `travis-test` script in `koa-openapi/package.json` to `npm run cover`?

**Comment by Manny651** [comment]
It seems that the koa-openapi tests fail on node v6 because they are using async functions (requires node 7)

**Comment by jsdevel** [comment]
@Manny651 looks like the v6 tests are failing on a few specs.  v6 is eol in april.  can you remove v6 from the .travis.yml file?  thanks for going the extra mile!

**Comment by jsdevel** [comment]
thanks @Manny651 !

**Comment by jsdevel** [comment]
published

**Pull request merged**
