### PR TITLE
feat(openapi-request-validator): allow null enums and nullable option

### LINKED ISSUE #397: Allow set nullable to request validator
### Problem

Request validator don't allow nullable fields

### Proposal

Convert OpenAPI specification to AJV type: ['whatever', 'null'] to allow nullable fields

I will do a PR ;)

### PR DESCRIPTION
**Pull request by javierblancosp**
- Allow nullable and null enums on the request validation

Closes #397

### CODE REVIEW

**Comment by jsdevel** [comment]
thanks!

**Comment by serbanmarti** [comment]
When do you plan on releasing a new version of the validator on npm?

**Comment by jsdevel** [comment]
hopefully soon

**Comment by serbanmarti** [comment]
Sorry to bug you again with the same question, but are there any plans on releasing an update with this fix soon?
We have a product that requires it, in order to be properly released.

**Comment by javierblancosp** [comment]
Hey, @serbanmarti, if you want i published a version with that in the mean time, until they published the changes ;) "@javi11/openapi-request-validator": "3.7.8",

**Comment by jsdevel** [comment]
latest changes have been published

**Pull request merged**
