### PR TITLE
openapi-framework: Log an improved warning if the operationId of an operation is not specified (fixes #465)

### LINKED ISSUE #465: Bad error message if operationId is not specified
When calling `initialize` with an `apiDoc` that has an operation that is missing an `operationId`, express-openapi emits a warning and then throws an exception. The warning is:

> Operation undefined not found in the operations parameter

The exception is:

> TypeError: Cannot read property 'undefined' of undefined

Neither is helpful in identifying the problem.

I have traced this issue into openapi-framework, so it is not specific to express-openapi.

### PR DESCRIPTION
**Pull request by michaellperry**
One new test. I opted to change just the warning and not the exception. If you feel that the exception should be changed as well, then an additional guard clause will need to be inserted.

### CODE REVIEW

**Comment by jsdevel** [comment]
this is great @michaellperry !  thanks!  i'll merge once the build passes.

**Comment by jsdevel** [comment]
@michaellperry can you fix the build?  i'll merge once it passes.

**Comment by michaellperry** [comment]
That did it. Looks like I forgot to run the linter.

**Comment by jsdevel** [comment]
thanks!

**Pull request merged**
