### PR TITLE
Request validator request body

### PR DESCRIPTION
**Pull request by bill-kitsune**
This is a step toward resolving #162 

My approach was to try to keep it backwards compatible, but I imagine that there could be a couple of different approaches to handling v3, so I'm hoping this at least starts the conversation.

### CODE REVIEW

**Comment by jsdevel** [comment]
nice work!  i'll publish later tonight

**Comment by jsdevel** [comment]
published in latest versions

**Comment by mbsimonovic** [comment]
this works fine for numbers but seems like it doesn't validate string's minimum and maximum lengths? Here's a demo:
```
const OpenAPIRequestValidator = require('openapi-request-validator');

const requestBodySpec ={
    "description": "request body",
    "required": true,
    "content": {
        "application/json": {
            "schema": {
                "type": "object",
                "required": [
                    "query"
                ],
                "properties": {
                    "query": {
                        "type": "string",
                        "minimum": 2,
                        "maximum": 1024
                    },
                    "maxResults": {
                        "description": "maximum entries",
                        "type": "integer",
                        "minimum": 1,
                        "default": 1000
                    }
                }
            }
        }
    }
};

var request = {
    headers: {
        'content-type':
            'application/json'
    },
    body: {
        query: 'a', // should fail, minimum length violated but DOESNT FAIL!?
        // query: new Array(150 + 1).join('1234567890'), // DOESNT FAIL!?
        // maxResults: 'a', // fails
    }
};

var errors = validator.validate(request);
console.log(errors); // => null, it's ok for foo to exist, and name is not required

```

Is this intentional or should I create a new issue?

**Comment by bill-kitsune** [comment]
@mbsimonovic not intentional just possibly incomplete.  I would open up a separate issue for this.

**Comment by mbsimonovic** [comment]
@bill-kitsune sure, https://github.com/kogosoftwarellc/open-api/issues/287

**Comment by mbsimonovic** [comment]
turned out to be a typo 😤

**Pull request merged**
